SET NAMES utf8mb4;
SET CHARACTER SET utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ──────────────────────────────
-- site_settings
-- ──────────────────────────────
TRUNCATE TABLE `site_settings`;
INSERT INTO `site_settings` (`id`, `key`, `value`, `type`, `group`, `label`, `description`, `created_at`, `updated_at`) VALUES ('1', 'site_name', 'Hamilton Beach Paraguay', 'text', 'general', 'Nombre del sitio', NULL, '2026-05-26 16:55:57', '2026-05-26 16:55:57');
INSERT INTO `site_settings` (`id`, `key`, `value`, `type`, `group`, `label`, `description`, `created_at`, `updated_at`) VALUES ('2', 'site_description', 'Distribuidor oficial en Paraguay. Electrodomésticos de calidad con respaldo y servicio técnico oficial.', 'text', 'general', 'Descripción del sitio', NULL, '2026-05-26 16:55:57', '2026-05-26 16:55:57');
INSERT INTO `site_settings` (`id`, `key`, `value`, `type`, `group`, `label`, `description`, `created_at`, `updated_at`) VALUES ('3', 'logo', '', 'file', 'general', 'Logo', NULL, '2026-05-26 16:55:57', '2026-05-26 16:55:57');
INSERT INTO `site_settings` (`id`, `key`, `value`, `type`, `group`, `label`, `description`, `created_at`, `updated_at`) VALUES ('4', 'favicon', '', 'file', 'general', 'Favicon', NULL, '2026-05-26 16:55:57', '2026-05-26 16:55:57');
INSERT INTO `site_settings` (`id`, `key`, `value`, `type`, `group`, `label`, `description`, `created_at`, `updated_at`) VALUES ('5', 'phone', '+595 (9) 1234-567', 'text', 'contact', 'Teléfono', NULL, '2026-05-26 16:55:57', '2026-05-26 16:55:57');
INSERT INTO `site_settings` (`id`, `key`, `value`, `type`, `group`, `label`, `description`, `created_at`, `updated_at`) VALUES ('6', 'whatsapp', '595911234567', 'text', 'contact', 'WhatsApp', NULL, '2026-05-26 16:55:57', '2026-05-26 16:55:57');
INSERT INTO `site_settings` (`id`, `key`, `value`, `type`, `group`, `label`, `description`, `created_at`, `updated_at`) VALUES ('7', 'email', 'info@hamiltonbeach.com.py', 'email', 'contact', 'Email público', NULL, '2026-05-26 16:55:57', '2026-05-26 16:55:57');
INSERT INTO `site_settings` (`id`, `key`, `value`, `type`, `group`, `label`, `description`, `created_at`, `updated_at`) VALUES ('8', 'contact_email', 'info@hamiltonbeach.com.py', 'email', 'contact', 'Email de recepción de formularios', NULL, '2026-05-26 16:55:57', '2026-05-26 16:55:57');
INSERT INTO `site_settings` (`id`, `key`, `value`, `type`, `group`, `label`, `description`, `created_at`, `updated_at`) VALUES ('9', 'address', 'Asunción, Paraguay', 'text', 'contact', 'Dirección', NULL, '2026-05-26 16:55:57', '2026-05-26 16:55:57');
INSERT INTO `site_settings` (`id`, `key`, `value`, `type`, `group`, `label`, `description`, `created_at`, `updated_at`) VALUES ('10', 'schedule', 'Lun–Vie: 9:00 – 18:00 hs\nSáb: 10:00 – 14:00 hs', 'textarea', 'contact', 'Horarios', NULL, '2026-05-26 16:55:57', '2026-05-26 16:55:57');
INSERT INTO `site_settings` (`id`, `key`, `value`, `type`, `group`, `label`, `description`, `created_at`, `updated_at`) VALUES ('11', 'instagram', 'https://instagram.com/hamiltonbeachpy', 'url', 'social', 'Instagram', NULL, '2026-05-26 16:55:57', '2026-05-26 16:55:57');
INSERT INTO `site_settings` (`id`, `key`, `value`, `type`, `group`, `label`, `description`, `created_at`, `updated_at`) VALUES ('12', 'facebook', 'https://facebook.com/hamiltonbeachpy', 'url', 'social', 'Facebook', NULL, '2026-05-26 16:55:57', '2026-05-26 16:55:57');
INSERT INTO `site_settings` (`id`, `key`, `value`, `type`, `group`, `label`, `description`, `created_at`, `updated_at`) VALUES ('13', 'tiktok', 'https://tiktok.com/@hamiltonbeachpy', 'url', 'social', 'TikTok', NULL, '2026-05-26 16:55:57', '2026-05-26 16:55:57');
INSERT INTO `site_settings` (`id`, `key`, `value`, `type`, `group`, `label`, `description`, `created_at`, `updated_at`) VALUES ('14', 'youtube', '', 'url', 'social', 'YouTube', NULL, '2026-05-26 16:55:57', '2026-05-26 16:55:57');
INSERT INTO `site_settings` (`id`, `key`, `value`, `type`, `group`, `label`, `description`, `created_at`, `updated_at`) VALUES ('15', 'twitter', '', 'url', 'social', 'Twitter / X', NULL, '2026-05-26 16:55:57', '2026-05-26 16:55:57');
INSERT INTO `site_settings` (`id`, `key`, `value`, `type`, `group`, `label`, `description`, `created_at`, `updated_at`) VALUES ('16', 'google_analytics_id', '', 'text', 'integrations', 'Google Analytics ID', NULL, '2026-05-26 16:55:57', '2026-05-26 16:55:57');
INSERT INTO `site_settings` (`id`, `key`, `value`, `type`, `group`, `label`, `description`, `created_at`, `updated_at`) VALUES ('17', 'meta_pixel_id', '', 'text', 'integrations', 'Meta Pixel ID', NULL, '2026-05-26 16:55:57', '2026-05-26 16:55:57');
INSERT INTO `site_settings` (`id`, `key`, `value`, `type`, `group`, `label`, `description`, `created_at`, `updated_at`) VALUES ('18', 'whatsapp_float_enabled', '1', 'boolean', 'integrations', 'WhatsApp flotante activo', NULL, '2026-05-26 16:55:57', '2026-05-26 16:55:57');
INSERT INTO `site_settings` (`id`, `key`, `value`, `type`, `group`, `label`, `description`, `created_at`, `updated_at`) VALUES ('19', 'custom_scripts_head', '', 'textarea', 'integrations', 'Scripts en <head>', NULL, '2026-05-26 16:55:57', '2026-05-26 16:55:57');
INSERT INTO `site_settings` (`id`, `key`, `value`, `type`, `group`, `label`, `description`, `created_at`, `updated_at`) VALUES ('20', 'custom_scripts_body', '', 'textarea', 'integrations', 'Scripts antes de </body>', NULL, '2026-05-26 16:55:57', '2026-05-26 16:55:57');
INSERT INTO `site_settings` (`id`, `key`, `value`, `type`, `group`, `label`, `description`, `created_at`, `updated_at`) VALUES ('21', 'home_features', '[{"icon":"location","title":"Puntos de venta en todo Paraguay","description":"Encontrá nuestros productos en tiendas autorizadas"},{"icon":"shield","title":"Garantía oficial 1 año","description":"Con respaldo de servicio técnico autorizado"},{"icon":"gear","title":"Servicio técnico oficial","description":"Técnicos capacitados con repuestos originales"}]', 'text', 'general', NULL, NULL, '2026-05-29 18:23:47', '2026-05-29 18:23:47');
INSERT INTO `site_settings` (`id`, `key`, `value`, `type`, `group`, `label`, `description`, `created_at`, `updated_at`) VALUES ('22', 'site_tagline', '', 'text', 'general', NULL, NULL, '2026-05-29 18:52:25', '2026-05-29 18:52:25');
INSERT INTO `site_settings` (`id`, `key`, `value`, `type`, `group`, `label`, `description`, `created_at`, `updated_at`) VALUES ('23', 'maintenance_mode', '0', 'text', 'general', NULL, NULL, '2026-05-29 18:58:37', '2026-06-01 11:45:31');
INSERT INTO `site_settings` (`id`, `key`, `value`, `type`, `group`, `label`, `description`, `created_at`, `updated_at`) VALUES ('24', 'hero_slide_interval', '6', 'text', 'general', NULL, NULL, '2026-06-01 13:09:53', '2026-06-01 13:09:53');

-- ──────────────────────────────
-- media
-- ──────────────────────────────
TRUNCATE TABLE `media`;
INSERT INTO `media` (`id`, `user_id`, `name`, `file_name`, `mime_type`, `path`, `disk`, `size`, `type`, `alt`, `title`, `caption`, `folder`, `conversions`, `created_at`, `updated_at`, `deleted_at`) VALUES ('1', '1', 'cafetera-retro-black-1', 'cafetera-retro-black-1.webp', 'image/webp', 'products/cafetera-retro-black-1.webp', 'public', '123672', 'image', 'cafetera-retro-black-1', NULL, NULL, 'products', NULL, '2026-05-26 18:54:34', '2026-05-26 18:54:34', NULL);
INSERT INTO `media` (`id`, `user_id`, `name`, `file_name`, `mime_type`, `path`, `disk`, `size`, `type`, `alt`, `title`, `caption`, `folder`, `conversions`, `created_at`, `updated_at`, `deleted_at`) VALUES ('2', '1', 'cafetera-retro-black-2', 'cafetera-retro-black-2.webp', 'image/webp', 'products/cafetera-retro-black-2.webp', 'public', '52212', 'image', 'cafetera-retro-black-2', NULL, NULL, 'products', NULL, '2026-05-26 18:54:34', '2026-05-26 18:54:34', NULL);
INSERT INTO `media` (`id`, `user_id`, `name`, `file_name`, `mime_type`, `path`, `disk`, `size`, `type`, `alt`, `title`, `caption`, `folder`, `conversions`, `created_at`, `updated_at`, `deleted_at`) VALUES ('3', '1', 'cafetera-retro-black-3', 'cafetera-retro-black-3.webp', 'image/webp', 'products/cafetera-retro-black-3.webp', 'public', '74490', 'image', 'cafetera-retro-black-3', NULL, NULL, 'products', NULL, '2026-05-26 18:54:34', '2026-05-26 18:54:34', NULL);
INSERT INTO `media` (`id`, `user_id`, `name`, `file_name`, `mime_type`, `path`, `disk`, `size`, `type`, `alt`, `title`, `caption`, `folder`, `conversions`, `created_at`, `updated_at`, `deleted_at`) VALUES ('4', '1', 'cafetera-retro-black-4', 'cafetera-retro-black-4.webp', 'image/webp', 'products/cafetera-retro-black-4.webp', 'public', '111272', 'image', 'cafetera-retro-black-4', NULL, NULL, 'products', NULL, '2026-05-26 18:54:34', '2026-05-26 18:54:34', NULL);
INSERT INTO `media` (`id`, `user_id`, `name`, `file_name`, `mime_type`, `path`, `disk`, `size`, `type`, `alt`, `title`, `caption`, `folder`, `conversions`, `created_at`, `updated_at`, `deleted_at`) VALUES ('5', '1', 'cafetera-retro-black-5', 'cafetera-retro-black-5.webp', 'image/webp', 'products/cafetera-retro-black-5.webp', 'public', '148446', 'image', 'cafetera-retro-black-5', NULL, NULL, 'products', NULL, '2026-05-26 18:54:34', '2026-05-26 18:54:34', NULL);
INSERT INTO `media` (`id`, `user_id`, `name`, `file_name`, `mime_type`, `path`, `disk`, `size`, `type`, `alt`, `title`, `caption`, `folder`, `conversions`, `created_at`, `updated_at`, `deleted_at`) VALUES ('6', '1', 'cafetera-retro-black-6', 'cafetera-retro-black-6.webp', 'image/webp', 'products/cafetera-retro-black-6.webp', 'public', '113902', 'image', 'cafetera-retro-black-6', NULL, NULL, 'products', NULL, '2026-05-26 18:54:34', '2026-05-26 18:54:34', NULL);
INSERT INTO `media` (`id`, `user_id`, `name`, `file_name`, `mime_type`, `path`, `disk`, `size`, `type`, `alt`, `title`, `caption`, `folder`, `conversions`, `created_at`, `updated_at`, `deleted_at`) VALUES ('7', '1', 'cafetera-home-barista', 'cafetera-home-barista.webp', 'image/webp', 'products/cafetera-home-barista.webp', 'public', '43904', 'image', 'cafetera-home-barista', NULL, NULL, 'products', NULL, '2026-05-26 18:54:34', '2026-05-26 18:54:34', NULL);
INSERT INTO `media` (`id`, `user_id`, `name`, `file_name`, `mime_type`, `path`, `disk`, `size`, `type`, `alt`, `title`, `caption`, `folder`, `conversions`, `created_at`, `updated_at`, `deleted_at`) VALUES ('8', '1', 'tostadora-silver', 'tostadora-silver.webp', 'image/webp', 'products/tostadora-silver.webp', 'public', '21102', 'image', 'tostadora-silver', NULL, NULL, 'products', NULL, '2026-05-26 18:54:34', '2026-05-26 18:54:34', NULL);
INSERT INTO `media` (`id`, `user_id`, `name`, `file_name`, `mime_type`, `path`, `disk`, `size`, `type`, `alt`, `title`, `caption`, `folder`, `conversions`, `created_at`, `updated_at`, `deleted_at`) VALUES ('9', '1', 'pava-cool-touch', 'pava-cool-touch.webp', 'image/webp', 'products/pava-cool-touch.webp', 'public', '26104', 'image', 'pava-cool-touch', NULL, NULL, 'products', NULL, '2026-05-26 18:54:34', '2026-05-26 18:54:34', NULL);
INSERT INTO `media` (`id`, `user_id`, `name`, `file_name`, `mime_type`, `path`, `disk`, `size`, `type`, `alt`, `title`, `caption`, `folder`, `conversions`, `created_at`, `updated_at`, `deleted_at`) VALUES ('10', '1', 'pava-double-wall', 'pava-double-wall.webp', 'image/webp', 'products/pava-double-wall.webp', 'public', '32402', 'image', 'pava-double-wall', NULL, NULL, 'products', NULL, '2026-05-26 18:54:34', '2026-05-26 18:54:34', NULL);
INSERT INTO `media` (`id`, `user_id`, `name`, `file_name`, `mime_type`, `path`, `disk`, `size`, `type`, `alt`, `title`, `caption`, `folder`, `conversions`, `created_at`, `updated_at`, `deleted_at`) VALUES ('11', '1', 'pava-digital', 'pava-digital.webp', 'image/webp', 'products/pava-digital.webp', 'public', '25972', 'image', 'pava-digital', NULL, NULL, 'products', NULL, '2026-05-26 18:54:34', '2026-05-26 18:54:34', NULL);

-- ──────────────────────────────
-- categories
-- ──────────────────────────────
TRUNCATE TABLE `categories`;
INSERT INTO `categories` (`id`, `type`, `name`, `slug`, `description`, `parent_id`, `order`, `is_active`, `meta_title`, `meta_description`, `created_at`, `updated_at`, `icon_type`, `icon`, `media_id`) VALUES ('1', 'product', 'Cafeteras', 'cafeteras', NULL, NULL, '1', '1', NULL, NULL, '2026-05-26 16:55:57', '2026-05-27 13:34:55', 'svg', 'coffee-maker.svg', NULL);
INSERT INTO `categories` (`id`, `type`, `name`, `slug`, `description`, `parent_id`, `order`, `is_active`, `meta_title`, `meta_description`, `created_at`, `updated_at`, `icon_type`, `icon`, `media_id`) VALUES ('2', 'product', 'Tostadoras', 'tostadoras', NULL, NULL, '2', '1', NULL, NULL, '2026-05-26 16:55:57', '2026-05-27 13:34:55', 'svg', 'toaster.svg', NULL);
INSERT INTO `categories` (`id`, `type`, `name`, `slug`, `description`, `parent_id`, `order`, `is_active`, `meta_title`, `meta_description`, `created_at`, `updated_at`, `icon_type`, `icon`, `media_id`) VALUES ('3', 'product', 'Pavas Eléctricas', 'pavas', NULL, NULL, '3', '1', NULL, NULL, '2026-05-26 16:55:57', '2026-05-27 13:34:55', 'svg', 'water-heater.svg', NULL);
INSERT INTO `categories` (`id`, `type`, `name`, `slug`, `description`, `parent_id`, `order`, `is_active`, `meta_title`, `meta_description`, `created_at`, `updated_at`, `icon_type`, `icon`, `media_id`) VALUES ('4', 'product', 'Molinillos', 'molinillos', NULL, NULL, '4', '1', NULL, NULL, '2026-05-26 16:55:57', '2026-05-27 13:34:55', 'svg', 'blender.svg', NULL);

-- ──────────────────────────────
-- products
-- ──────────────────────────────
TRUNCATE TABLE `products`;
INSERT INTO `products` (`id`, `user_id`, `category_id`, `media_id`, `title`, `subtitle`, `content`, `slug`, `status`, `order`, `is_featured`, `attachment`, `price`, `specifications`, `meta_title`, `meta_description`, `og_title`, `og_description`, `og_image`, `no_index`, `created_at`, `updated_at`, `deleted_at`, `retailers`) VALUES ('1', '1', '1', '1', 'Cafetera Espresso Retro Black', 'Cafetera de estilo retro en acabado negro mate. Tecnología de extracción óptima para una taza con sabor rico y aromático. Capacidad para 10 tazas, fácil de usar y limpiar, con piezas desmontables compatibles con lavavajillas.', '<p>Descubr&iacute; la <strong>Cafetera Retro Black</strong>, el complemento perfecto para los amantes del caf&eacute; que buscan un toque de estilo vintage en su cocina.</p>\r\n<h2>Caracter&iacute;sticas principales</h2>\r\n<ul>\r\n<li><strong>Dise&ntilde;o retro en negro mate</strong> con l&iacute;neas cl&aacute;sicas que agregan sofisticaci&oacute;n a tu cocina.</li>\r\n<li><strong>Capacidad para 10 tazas</strong> (dep&oacute;sito de 1.2 L), ideal para toda la familia.</li>\r\n<li><strong>Tecnolog&iacute;a de extracci&oacute;n &oacute;ptima</strong> para una taza con sabor rico y arom&aacute;tico.</li>\r\n<li>Piezas desmontables <strong>compatibles con lavavajillas</strong> para una limpieza sin esfuerzo.</li>\r\n</ul>', 'cafetera-espresso-retro-black', 'published', '1', '1', NULL, '850000', '<h2>Especificaciones t&eacute;cnicas</h2><table><tbody><tr><td><strong>Modelo</strong></td><td>Retro Black – 40730</td></tr><tr><td><strong>Color</strong></td><td>Negro mate</td></tr><tr><td><strong>Capacidad</strong></td><td>Hasta 10 tazas (1.2 L)</td></tr><tr><td><strong>Material</strong></td><td>Acero inoxidable y plástico ABS</td></tr><tr><td><strong>Voltaje</strong></td><td>220 V / 50 Hz</td></tr></tbody></table>', NULL, NULL, NULL, NULL, NULL, '0', '2026-05-26 16:55:58', '2026-05-29 17:05:37', NULL, '[{"name":"Super 6","url":"https:\\/\\/www.superseis.com.py"}]');
INSERT INTO `products` (`id`, `user_id`, `category_id`, `media_id`, `title`, `subtitle`, `content`, `slug`, `status`, `order`, `is_featured`, `attachment`, `price`, `specifications`, `meta_title`, `meta_description`, `og_title`, `og_description`, `og_image`, `no_index`, `created_at`, `updated_at`, `deleted_at`, `retailers`) VALUES ('2', '1', '1', '7', 'Cafetera Home Barista 7-in-1', 'La experiencia de un barista profesional en tu hogar. 7 funciones en un solo equipo para preparar todo tipo de bebidas de café.', '<p>La <strong>Cafetera Home Barista 7-in-1</strong> te permite preparar espresso, cappuccino, latte y más desde la comodidad de tu hogar con resultados profesionales.</p><h2>Características principales</h2><ul><li><strong>7 funciones</strong>: espresso, americano, cappuccino, latte, café negro, café con leche y bebida caliente.</li><li>Pantalla digital con controles intuitivos.</li><li>Depósito de agua extraíble de 1.5 L.</li><li>Vaporizador de leche integrado.</li></ul>', 'cafetera-home-barista-7-in-1', 'published', '2', '1', NULL, '1200000', '<h2>Especificaciones t&eacute;cnicas</h2><table><tbody><tr><td><strong>Modelo</strong></td><td>Home Barista 7-in-1</td></tr><tr><td><strong>Funciones</strong></td><td>7 modos de preparación</td></tr><tr><td><strong>Capacidad</strong></td><td>1.5 L</td></tr><tr><td><strong>Voltaje</strong></td><td>220 V / 50 Hz</td></tr></tbody></table>', NULL, NULL, NULL, NULL, NULL, '0', '2026-05-26 16:55:58', '2026-05-29 17:05:37', NULL, NULL);
INSERT INTO `products` (`id`, `user_id`, `category_id`, `media_id`, `title`, `subtitle`, `content`, `slug`, `status`, `order`, `is_featured`, `attachment`, `price`, `specifications`, `meta_title`, `meta_description`, `og_title`, `og_description`, `og_image`, `no_index`, `created_at`, `updated_at`, `deleted_at`, `retailers`) VALUES ('3', '1', '2', '8', 'Tostadora Toaster Silver', 'Tostadora de 2 ranuras en acabado plateado. Control de dorado ajustable en 7 niveles, bandeja recogemigas desmontable.', '<p>La <strong>Tostadora Toaster Silver</strong> combina diseño elegante con funcionalidad práctica. Perfecta para el desayuno diario.</p><h2>Características principales</h2><ul><li>2 ranuras extra anchas para todo tipo de pan.</li><li>7 niveles de dorado ajustable.</li><li>Función descongelación y recalentamiento.</li><li>Bandeja recogemigas desmontable y lavable.</li></ul>', 'tostadora-toaster-silver', 'published', '3', '1', NULL, '320000', '<h2>Especificaciones t&eacute;cnicas</h2><table><tbody><tr><td><strong>Modelo</strong></td><td>Toaster Silver</td></tr><tr><td><strong>Color</strong></td><td>Plateado</td></tr><tr><td><strong>Ranuras</strong></td><td>2 ranuras extra anchas</td></tr><tr><td><strong>Niveles</strong></td><td>7 niveles de dorado</td></tr><tr><td><strong>Voltaje</strong></td><td>220 V / 50 Hz</td></tr></tbody></table>', NULL, NULL, NULL, NULL, NULL, '0', '2026-05-26 16:55:58', '2026-05-29 17:05:37', NULL, NULL);
INSERT INTO `products` (`id`, `user_id`, `category_id`, `media_id`, `title`, `subtitle`, `content`, `slug`, `status`, `order`, `is_featured`, `attachment`, `price`, `specifications`, `meta_title`, `meta_description`, `og_title`, `og_description`, `og_image`, `no_index`, `created_at`, `updated_at`, `deleted_at`, `retailers`) VALUES ('4', '1', '3', '9', 'Pava Eléctrica Cool-Touch', 'Pava eléctrica con tecnología Cool-Touch que mantiene el exterior frío al tacto incluso cuando el agua está caliente.', '<p>La <strong>Pava Cool-Touch</strong> es ideal para familias con niños gracias a su tecnología de doble pared que mantiene el exterior frío al tacto.</p><h2>Características principales</h2><ul><li>Tecnología Cool-Touch: exterior frío al tacto.</li><li>Capacidad de 1.7 litros.</li><li>Apagado automático y protección contra ebullición en seco.</li><li>Filtro anti-cal desmontable.</li></ul>', 'pava-electrica-cool-touch', 'published', '4', '1', NULL, '280000', '<h2>Especificaciones t&eacute;cnicas</h2><table><tbody><tr><td><strong>Modelo</strong></td><td>Cool-Touch</td></tr><tr><td><strong>Capacidad</strong></td><td>1.7 L</td></tr><tr><td><strong>Potencia</strong></td><td>2200 W</td></tr><tr><td><strong>Voltaje</strong></td><td>220 V / 50 Hz</td></tr></tbody></table>', NULL, NULL, NULL, NULL, NULL, '0', '2026-05-26 16:55:58', '2026-05-29 17:05:37', NULL, NULL);
INSERT INTO `products` (`id`, `user_id`, `category_id`, `media_id`, `title`, `subtitle`, `content`, `slug`, `status`, `order`, `is_featured`, `attachment`, `price`, `specifications`, `meta_title`, `meta_description`, `og_title`, `og_description`, `og_image`, `no_index`, `created_at`, `updated_at`, `deleted_at`, `retailers`) VALUES ('5', '1', '3', '10', 'Pava Eléctrica Double-Wall', 'Pava de doble pared que conserva la temperatura del agua caliente por más tiempo. Diseño moderno en acero inoxidable.', '<p>La <strong>Pava Double-Wall</strong> mantiene el agua caliente por m&aacute;s tiempo gracias a su construcci&oacute;n de doble pared en acero inoxidable.</p>\r\n<h2>Caracter&iacute;sticas principales</h2>\r\n<ul>\r\n<li>Doble pared para mayor conservaci&oacute;n del calor.</li>\r\n<li>Capacidad de 1.5 litros.</li>\r\n<li>Base giratoria 360&deg;.</li>\r\n<li>Apagado autom&aacute;tico al hervir.</li>\r\n</ul>', 'pava-electrica-double-wall', 'published', '5', '1', NULL, '350000', '<h2>Especificaciones t&eacute;cnicas</h2>\r\n<table>\r\n<tbody>\r\n<tr>\r\n<td><strong>Modelo</strong></td>\r\n<td>Double-Wall</td>\r\n</tr>\r\n<tr>\r\n<td><strong>Capacidad</strong></td>\r\n<td>1.5 L</td>\r\n</tr>\r\n<tr>\r\n<td><strong>Material</strong></td>\r\n<td>Acero inoxidable doble pared</td>\r\n</tr>\r\n<tr>\r\n<td><strong>Voltaje</strong></td>\r\n<td>220 V / 50 Hz</td>\r\n</tr>\r\n</tbody>\r\n</table>', NULL, NULL, NULL, NULL, NULL, '0', '2026-05-26 16:55:58', '2026-06-01 16:36:19', NULL, NULL);
INSERT INTO `products` (`id`, `user_id`, `category_id`, `media_id`, `title`, `subtitle`, `content`, `slug`, `status`, `order`, `is_featured`, `attachment`, `price`, `specifications`, `meta_title`, `meta_description`, `og_title`, `og_description`, `og_image`, `no_index`, `created_at`, `updated_at`, `deleted_at`, `retailers`) VALUES ('6', '1', '4', '11', 'Molinillo de Café Profesional', 'Molinillo de café con cuchillas de acero inoxidable. 18 ajustes de grosor para espresso, cafetera y prensa francesa.', '<p>El <strong>Molinillo de Caf&eacute; Profesional</strong> te permite moler los granos al nivel perfecto para cada m&eacute;todo de preparaci&oacute;n.</p>\r\n<h2>Caracter&iacute;sticas principales</h2>\r\n<ul>\r\n<li>18 ajustes de grosor: de fino (espresso) a grueso (prensa francesa).</li>\r\n<li>Cuchillas de acero inoxidable de larga duraci&oacute;n.</li>\r\n<li>Capacidad para 100 g de caf&eacute;.</li>\r\n<li>Temporizador integrado para porciones exactas.</li>\r\n</ul>', 'molinillo-de-cafe-profesional', 'published', '6', '1', NULL, '450000', '<h2>Especificaciones t&eacute;cnicas</h2>\r\n<table>\r\n<tbody>\r\n<tr>\r\n<td><strong>Modelo</strong></td>\r\n<td>Molinillo Profesional</td>\r\n</tr>\r\n<tr>\r\n<td><strong>Ajustes</strong></td>\r\n<td>18 niveles de grosor</td>\r\n</tr>\r\n<tr>\r\n<td><strong>Capacidad</strong></td>\r\n<td>100 g</td>\r\n</tr>\r\n<tr>\r\n<td><strong>Potencia</strong></td>\r\n<td>150 W</td>\r\n</tr>\r\n<tr>\r\n<td><strong>Voltaje</strong></td>\r\n<td>220 V / 50 Hz</td>\r\n</tr>\r\n</tbody>\r\n</table>', NULL, NULL, NULL, NULL, NULL, '0', '2026-05-26 16:55:58', '2026-06-01 16:36:26', NULL, NULL);
INSERT INTO `products` (`id`, `user_id`, `category_id`, `media_id`, `title`, `subtitle`, `content`, `slug`, `status`, `order`, `is_featured`, `attachment`, `price`, `specifications`, `meta_title`, `meta_description`, `og_title`, `og_description`, `og_image`, `no_index`, `created_at`, `updated_at`, `deleted_at`, `retailers`) VALUES ('7', '1', '1', NULL, 'prueba', 'prueba', '<p>descripcion larga&nbsp;</p>\r\n<h2><span style="text-decoration: underline;"><strong>Titulo&nbsp;</strong></span></h2>\r\n<p>esto es de prueba</p>', 'prueba', 'published', '0', '0', NULL, '850000', NULL, NULL, NULL, NULL, NULL, NULL, '0', '2026-05-27 14:12:07', '2026-05-27 14:12:25', '2026-05-27 14:12:25', NULL);

-- ──────────────────────────────
-- product_media
-- ──────────────────────────────
TRUNCATE TABLE `product_media`;
INSERT INTO `product_media` (`id`, `product_id`, `media_id`, `order`, `created_at`, `updated_at`) VALUES ('7', '2', '7', '0', NULL, NULL);
INSERT INTO `product_media` (`id`, `product_id`, `media_id`, `order`, `created_at`, `updated_at`) VALUES ('8', '3', '8', '0', NULL, NULL);
INSERT INTO `product_media` (`id`, `product_id`, `media_id`, `order`, `created_at`, `updated_at`) VALUES ('9', '4', '9', '0', NULL, NULL);
INSERT INTO `product_media` (`id`, `product_id`, `media_id`, `order`, `created_at`, `updated_at`) VALUES ('10', '5', '10', '0', NULL, NULL);
INSERT INTO `product_media` (`id`, `product_id`, `media_id`, `order`, `created_at`, `updated_at`) VALUES ('11', '6', '11', '0', NULL, NULL);
INSERT INTO `product_media` (`id`, `product_id`, `media_id`, `order`, `created_at`, `updated_at`) VALUES ('12', '1', '1', '0', NULL, NULL);
INSERT INTO `product_media` (`id`, `product_id`, `media_id`, `order`, `created_at`, `updated_at`) VALUES ('13', '1', '2', '1', NULL, NULL);
INSERT INTO `product_media` (`id`, `product_id`, `media_id`, `order`, `created_at`, `updated_at`) VALUES ('14', '1', '3', '2', NULL, NULL);
INSERT INTO `product_media` (`id`, `product_id`, `media_id`, `order`, `created_at`, `updated_at`) VALUES ('15', '1', '4', '3', NULL, NULL);
INSERT INTO `product_media` (`id`, `product_id`, `media_id`, `order`, `created_at`, `updated_at`) VALUES ('16', '1', '5', '4', NULL, NULL);
INSERT INTO `product_media` (`id`, `product_id`, `media_id`, `order`, `created_at`, `updated_at`) VALUES ('17', '1', '6', '5', NULL, NULL);

-- ──────────────────────────────
-- faqs
-- ──────────────────────────────
TRUNCATE TABLE `faqs`;
INSERT INTO `faqs` (`id`, `question`, `answer`, `category`, `order`, `is_active`, `created_at`, `updated_at`) VALUES ('1', '¿Dónde puedo comprar los productos Hamilton Beach en Paraguay?', 'Los productos Hamilton Beach están disponibles en nuestros puntos de venta autorizados en todo el país. En cada ficha de producto encontrarás los enlaces a los puntos de venta donde podés adquirirlo. También podés consultarnos directamente por WhatsApp para saber el punto más cercano a tu ubicación.', 'general', '2', '1', '2026-05-26 16:55:58', '2026-06-02 13:33:32');
INSERT INTO `faqs` (`id`, `question`, `answer`, `category`, `order`, `is_active`, `created_at`, `updated_at`) VALUES ('2', '¿Qué garantía tienen los productos?', 'Todos los productos Hamilton Beach vendidos a través de distribuidores autorizados en Paraguay cuentan con garantía oficial de 1 año que cubre defectos de fabricación y problemas de funcionamiento. La garantía no cubre daños por mal uso, accidentes, voltaje inadecuado ni desgaste natural. Consultá la póliza completa en nuestra sección de Garantía.', 'garantia', '1', '1', '2026-05-26 16:55:58', '2026-06-02 13:33:32');
INSERT INTO `faqs` (`id`, `question`, `answer`, `category`, `order`, `is_active`, `created_at`, `updated_at`) VALUES ('3', '¿Cómo valido la garantía de mi producto?', 'Para validar la garantía necesitás conservar la factura de compra emitida por el punto de venta autorizado y la póliza de garantía. Si perdiste la póliza, podemos emitir una nueva contra la presentación de la factura original. Contactanos por WhatsApp o formulario de contacto.', 'garantia', '3', '1', '2026-05-26 16:55:58', '2026-06-02 13:33:32');
INSERT INTO `faqs` (`id`, `question`, `answer`, `category`, `order`, `is_active`, `created_at`, `updated_at`) VALUES ('4', '¿Tienen servicio técnico oficial en Paraguay?', 'Sí, contamos con servicio técnico oficial con técnicos capacitados por Hamilton Beach. Realizamos diagnóstico gratuito, reparaciones con repuestos originales y ofrecemos 90 días de garantía sobre la reparación. Para solicitar el servicio contactanos por WhatsApp o completá el formulario de contacto.', 'servicio', '4', '1', '2026-05-26 16:55:58', '2026-06-02 13:33:32');
INSERT INTO `faqs` (`id`, `question`, `answer`, `category`, `order`, `is_active`, `created_at`, `updated_at`) VALUES ('5', '¿Cómo obtengo el manual de uso de mi producto?', 'Los manuales de uso están disponibles en la ficha de cada producto en nuestro catálogo. Ingresá a la sección Productos, encontrá tu modelo y descargá el PDF desde el enlace al final de la descripción. También podés visitar nuestra sección de Manuales de Producto para obtener más información.', 'productos', '5', '1', '2026-05-26 16:55:58', '2026-06-02 13:33:32');
INSERT INTO `faqs` (`id`, `question`, `answer`, `category`, `order`, `is_active`, `created_at`, `updated_at`) VALUES ('6', '¿Qué hago si mi producto presenta una falla?', 'Si tu producto presenta una falla, seguí estos pasos: 1) Revisá el manual de uso por si es un problema de configuración o uso. 2) Si el equipo está dentro del período de garantía, contactanos con la factura y póliza de garantía. 3) Nuestro equipo técnico te asesorará sobre el proceso de reparación sin costo. Contactanos por WhatsApp o formulario.', 'servicio', '6', '1', '2026-05-26 16:55:58', '2026-06-02 13:33:32');
INSERT INTO `faqs` (`id`, `question`, `answer`, `category`, `order`, `is_active`, `created_at`, `updated_at`) VALUES ('7', '¿Venden repuestos y accesorios?', 'Sí, contamos con repuestos originales Hamilton Beach. Para consultar disponibilidad del repuesto que necesitás, contactanos por WhatsApp indicando el modelo de tu equipo y la pieza requerida.', 'productos', '7', '1', '2026-05-26 16:55:58', '2026-06-02 13:33:32');
INSERT INTO `faqs` (`id`, `question`, `answer`, `category`, `order`, `is_active`, `created_at`, `updated_at`) VALUES ('8', '¿Tienen descuentos para empresas o compras al por mayor?', 'Sí, ofrecemos condiciones especiales para empresas, instituciones y revendedores. Para recibir una cotización personalizada, contactanos por email a info@hamiltonbeach.com.py indicando los productos de interés y las cantidades.', 'general', '8', '1', '2026-05-26 16:55:58', '2026-06-02 13:33:32');

-- ──────────────────────────────
-- pages
-- ──────────────────────────────
TRUNCATE TABLE `pages`;
INSERT INTO `pages` (`id`, `user_id`, `media_id`, `section`, `title`, `subtitle`, `content`, `slug`, `status`, `order`, `meta_title`, `meta_description`, `og_title`, `og_description`, `og_image`, `no_index`, `created_at`, `updated_at`, `deleted_at`, `icon`) VALUES ('1', '1', NULL, 'servicio-tecnico', 'Servicio Técnico', 'Reparaciones con repuestos originales', '<p>Contamos con <strong>técnicos capacitados y certificados por Hamilton Beach</strong> para garantizar el correcto funcionamiento de tus electrodomésticos, utilizando únicamente repuestos originales de la marca.</p><h2>¿Qué incluye nuestro servicio?</h2><ul><li><strong>Diagnóstico gratuito</strong> — evaluamos el estado de tu equipo sin costo.</li><li><strong>Repuestos originales Hamilton Beach</strong> — calidad y durabilidad garantizada.</li><li><strong>Garantía de reparación de 90 días</strong> sobre mano de obra y repuestos utilizados.</li><li>Atención personalizada por técnicos autorizados por la marca.</li></ul><h2>¿Cómo solicitar el servicio?</h2><ol><li>Contactanos por WhatsApp o teléfono describiendo el problema y el modelo de tu equipo.</li><li>Nuestro equipo técnico evalúa el equipo y te informa el presupuesto sin compromiso.</li><li>Una vez aprobado, realizamos la reparación con repuestos originales Hamilton Beach.</li><li>Retirás tu equipo funcionando con garantía de 90 días sobre la reparación realizada.</li></ol>', 'servicio-tecnico', 'published', '1', NULL, NULL, NULL, NULL, NULL, '0', '2026-05-26 16:55:58', '2026-05-27 12:49:34', NULL, 'M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z||M15 12a3 3 0 11-6 0 3 3 0 016 0z');
INSERT INTO `pages` (`id`, `user_id`, `media_id`, `section`, `title`, `subtitle`, `content`, `slug`, `status`, `order`, `meta_title`, `meta_description`, `og_title`, `og_description`, `og_image`, `no_index`, `created_at`, `updated_at`, `deleted_at`, `icon`) VALUES ('2', '1', NULL, 'manuales', 'Manuales', 'Guías de uso de todos los productos', '<p>Cada producto Hamilton Beach incluye un <strong>manual de uso</strong> con información detallada sobre su funcionamiento, recomendaciones de seguridad y consejos de mantenimiento.</p><h2>¿Cómo encontrar el manual de tu producto?</h2><ol><li>Ingresá a la sección <a href="/productos">Productos</a> y encontrá el modelo de tu electrodoméstico Hamilton Beach.</li><li>Hacé clic en el producto para ver toda la información, características y especificaciones técnicas.</li><li>Al final de la descripción encontrarás el enlace para descargar el manual de uso en formato PDF.</li></ol><h2>¿Por qué es importante leer el manual?</h2><ul><li>Asegura el uso correcto y seguro del electrodoméstico.</li><li>Prolonga la vida útil de tu producto.</li><li>Contiene advertencias de seguridad importantes.</li><li>Es requerido para validar la garantía en caso de reclamo.</li><li>Incluye guías de limpieza y mantenimiento.</li><li>Describe todas las funciones y modos de operación.</li></ul><p><strong>Recomendación:</strong> Conservá el manual impreso en un lugar seguro junto con la factura de compra y la póliza de garantía.</p>', 'manuales-de-producto', 'published', '2', NULL, NULL, NULL, NULL, NULL, '0', '2026-05-26 16:55:58', '2026-05-27 12:49:34', NULL, 'M12 6.253v13m0-13C10.832 5.477 9.246 5 7.5 5S4.168 5.477 3 6.253v13C4.168 18.477 5.754 18 7.5 18s3.332.477 4.5 1.253m0-13C13.168 5.477 14.754 5 16.5 5c1.747 0 3.332.477 4.5 1.253v13C19.832 18.477 18.247 18 16.5 18c-1.746 0-3.332.477-4.5 1.253');
INSERT INTO `pages` (`id`, `user_id`, `media_id`, `section`, `title`, `subtitle`, `content`, `slug`, `status`, `order`, `meta_title`, `meta_description`, `og_title`, `og_description`, `og_image`, `no_index`, `created_at`, `updated_at`, `deleted_at`, `icon`) VALUES ('3', '1', NULL, 'garantia', 'Garantías', 'Póliza y condiciones de garantía oficial', '<p><strong>Importante:</strong> Conservá este documento junto con la factura de compra. En caso de pérdida de la póliza, el distribuidor podrá emitir una nueva contra presentación de la factura original.</p><h2>¿Qué cubre la garantía?</h2><ul><li>Defectos de fabricación en materiales y mano de obra.</li><li>Fallas en el funcionamiento normal del equipo.</li><li>Reemplazo de partes y componentes defectuosos.</li><li>Mano de obra dentro de la red de servicio autorizado.</li></ul><h2>¿Qué NO cubre la garantía?</h2><ul><li>Daños por uso incorrecto o negligencia.</li><li>Daños por voltaje inadecuado o sobretensión.</li><li>Reparaciones realizadas por técnicos no autorizados.</li><li>Daños estéticos (rayones, golpes, decoloración).</li><li>Productos con número de serie alterado o removido.</li><li>Desgaste natural por uso normal.</li></ul><h2>¿Cómo hacer un reclamo de garantía?</h2><ol><li>Contactanos por teléfono, WhatsApp o formulario de contacto indicando el modelo del equipo y la falla.</li><li>Tené a mano la factura de compra y la póliza de garantía para agilizar el proceso.</li><li>Nuestro equipo coordinará la revisión del equipo. El plazo máximo de reparación bajo garantía es de 30 días hábiles.</li><li>Una vez reparado, recibirás tu equipo en perfectas condiciones sin costo adicional.</li></ol>', 'garantia-de-producto', 'published', '3', NULL, NULL, NULL, NULL, NULL, '0', '2026-05-26 16:55:58', '2026-05-27 12:49:34', NULL, 'M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z');
INSERT INTO `pages` (`id`, `user_id`, `media_id`, `section`, `title`, `subtitle`, `content`, `slug`, `status`, `order`, `meta_title`, `meta_description`, `og_title`, `og_description`, `og_image`, `no_index`, `created_at`, `updated_at`, `deleted_at`, `icon`) VALUES ('5', '1', NULL, 'preguntas-frecuentes', 'Preguntas Frecuentes', 'Respuestas a las consultas más comunes', NULL, 'preguntas-frecuentes', 'published', '4', NULL, NULL, NULL, NULL, NULL, '0', '2026-05-27 12:49:34', '2026-05-27 12:49:34', NULL, 'M8.228 9c.549-1.165 2.03-2 3.772-2 2.21 0 4 1.343 4 3 0 1.4-1.278 2.575-3.006 2.907-.542.104-.994.54-.994 1.093m0 3h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z');

-- ──────────────────────────────
-- banners
-- ──────────────────────────────
TRUNCATE TABLE `banners`;
INSERT INTO `banners` (`id`, `media_id`, `title`, `subtitle`, `description`, `cta_text`, `cta_url`, `position`, `order`, `is_active`, `created_at`, `updated_at`, `tagline`, `cta2_text`, `cta2_url`) VALUES ('1', '1', 'Calidad Hamilton Beach', 'para tu hogar', 'Cafeteras, tostadoras, pavas eléctricas y molinillos de café con respaldo y garantía oficial en Paraguay.', 'Ver catálogo', '/productos', 'home', '3', '1', '2026-05-26 16:55:58', '2026-06-01 13:35:58', NULL, 'Contacto', '/contacto');

-- ──────────────────────────────
-- announcements
-- ──────────────────────────────
TRUNCATE TABLE `announcements`;
INSERT INTO `announcements` (`id`, `text`, `order`, `is_active`, `created_at`, `updated_at`) VALUES ('1', 'DISTRIBUIDOR OFICIAL HAMILTON BEACH® EN PARAGUAY', '1', '1', '2026-05-27 13:11:18', '2026-05-27 13:11:18');
INSERT INTO `announcements` (`id`, `text`, `order`, `is_active`, `created_at`, `updated_at`) VALUES ('2', 'GARANTÍA 1 AÑO CON SERVICIO TÉCNICO OFICIAL', '2', '1', '2026-05-27 13:11:18', '2026-05-27 13:11:18');

SET FOREIGN_KEY_CHECKS = 1;
