allowBuilds:
  esbuild: true

overrides:
  form-data@>=4.0.0 <4.0.6: ">=4.0.6"
  baseline-browser-mapping@>=2.0.0 <2.11.0: ">=2.11.0"
  browserslist@<=4.28.6: ">=4.28.7"
  shell-quote@<=1.8.4: ">=1.8.5"
